# Generated by Django 5.1 on 2024-08-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_orderstats_last_updated_proposalstats_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstats',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderstats',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposalstats',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proposalstats',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
